placeholders:
    oro_user_view_additional_data:
        items:
            acme_task_assigned_tasks:
                order: 50
    view_navButtons_after:
        items:
            acme_task_create_user_task_button:
                order: 50

items:
    acme_task_assigned_tasks:
        template: AcmeTaskBundle:Task:assignedTasks.html.twig
    acme_task_create_user_task_button:
        template: AcmeTaskBundle:Task:createUserTaskButton.html.twig
