parameters:
    acme_task.entity.class: Acme\Bundle\TaskBundle\Entity\Task

    acme_task.form.type.task.class: Acme\Bundle\TaskBundle\Form\Type\TaskType
    acme_task.form.type.task_api.class: Acme\Bundle\TaskBundle\Form\Type\TaskApiType

    acme_task.statistics.class: Acme\Bundle\TaskBundle\Model\Statistics

services:
    acme_task.form.type.task:
        class: %acme_task.form.type.task.class%
        arguments:
            - %acme_task.entity.class%
        tags:
            - { name: form.type, alias: acme_task }

    acme_task.form.type.task_api:
        class: %acme_task.form.type.task_api.class%
        tags:
            - { name: form.type, alias: acme_task_api }

    acme_task.statistics:
        class: %acme_task.statistics.class%
        arguments:
            - @doctrine.orm.entity_manager
