acme_task_bundle:
    resource:     "@AcmeTaskBundle/Controller"
    type:         annotation
    prefix:       /acme

acme_task_bundle_api:
    resource:     "@AcmeTaskBundle/Controller/Api/Rest/TaskController.php"
    type:         rest
    prefix:       api/rest/{version}/acme
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
